<?php
/**
 * Copyright © 2016 Innovo. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Set active item in topmenu template
 *
 * @var $block \Innovo\CacheImprove\Block\Theme\Html\Topmenu\ActiveItemJs
 */
if (!$block->getCssActive() && !$block->getCssHasActive()) {
    return '';
}
?>
<script>
    if (
        window.innvConfig &&
        window.innvConfig.ciCurrentCategory
    ) {
        require(['jquery'], function($jqry) {
            try {
                var cssActive = '<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getCssActive())?>';
                var cssHasActive = '<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getCssHasActive())?>';
                var jsSelector = <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getJsSelector())?>;
                var jsParentsSelector = <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getJsParentsSelector())?>;

                for (var i = 0; i < jsSelector.length; i++) {
                    var jsSel = jsSelector[i];
                    var tmenu = $jqry(jsSel);
                    if (tmenu) {
                        var citem = tmenu.find(
                            '.innv-category-node-' + window.innvConfig.ciCurrentCategory
                        );
                        if (citem.length > 0) {
                            if (cssActive) {
                                citem.addClass(cssActive);
                            }
                            if (cssHasActive && jsParentsSelector.length) {
                                for (var j = 0; j < jsParentsSelector.length; j++) {
                                    var jsParentSel = jsParentsSelector[j];
                                    var cparents = citem.parents(jsParentSel);
                                    if (cparents && cparents.length) {
                                        cparents.each(function (key, el) {
                                            el = $jqry(el);
                                            if (cssActive) {
                                                if (!el.hasClass(cssActive)) {
                                                    el.addClass(cssHasActive);
                                                }
                                            } else{
                                                el.addClass(cssHasActive);
                                            }
                                        });
                                    }
                                }
                            }

                        }

                    }
                }
            } catch (err) {
                console.log(err.message)
            }
        });
    }
</script>
